import Head from 'next/head'

import Container from '../components/Container'
import Footer from '../components/Footer'
import Header from '../components/Header'

const Home = () => {
  return (
    <div>
      <Head>
        <title>torik135 - All Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Container />
      <Footer />
    </div>
  )
}


export default Home